### ISSUE TITLE
Not Syncing up Asus - Corsair

### ISSUE THREAD

**Issue by danielriddell21** [DarthAffe/RGBSyncPlus#29]
I have ran in admin and downgraded my aura and put the device files in the folder but nothing appears

edit, got it to show devices, but not syncing

I am trying to sync my Asus Strix Z370-E to my Corsair H150i pro

**Comment by bobland1** [comment]
![image](https://user-images.githubusercontent.com/25375432/51851891-c274c600-231c-11e9-967c-96fc5e8c1eca.png)

**Comment by ericnewton76** [comment]
I have cooler master rgb hub that its not detecting... schucks!

**Comment by zabilac630** [comment]
Worth noting that it only works if you select option 3 or lower in AURA, nothing like Color Cycle works
