### ISSUE TITLE
No Available LEDs?

### ISSUE THREAD

**Issue by Neudels** [DarthAffe/RGBSyncPlus#32]
**N00b Warning!**

I downloaded v. 1.0.0.2, unpacked everything, and ran the .exe as admin, but there are no LEDs listed to sync.. I have an ASUS Prime Z270-A mobo, Razer Blackwidow Chroma V2 keys, and a Logitech G502 mouse. None of them are showing up as available to sync. Nothing in the "Sync-LED" dropdown menu either. When I go to the settings page, there is nothing listed under "Devices:"

I feel like I must be missing something obvious. 

Thanks for all your help. Godspeed.

**Comment by DarthAffe** [comment]
You have to unblock the zip before extracting it. (Right click, go to properties, unblock the zip)

**Comment by Neudels** [comment]
That worked, thanks! 10/10 helpful

**Comment by Dadudze123** [comment]
I have the same proble, but I don't have unblock button there
