### ISSUE TITLE
No Settings.json

### ISSUE THREAD

**Issue by Dadudze123** [DarthAffe/RGBSyncPlus#35]
When I am right clicking on icon nothing appears. There is no file named Settings.json, so I can't change "MinimizeToTray":true to "MinimizeToTray":false
I have downloaded it again and launched it without unblocking. Now it works, but don't detect any leds
Hardware:
- Graphics card led
- Keyboard (Razer BW Chroma V2)
- Mouse (Razer DeathAdder Elite)
- Mousepad (Razer FireFly Cloth Edition)
- Headset (Razer Nari Ultimate)

**Comment by DarthAffe** [comment]
To get the Settings.json you need to run and close the application one time (rightclick exit).
If that's not possible you can try to create it yourself with the following content `{"Version":1,"UpdateRate":30.0,"MinimizeToTray":false,"SyncGroups":[]}`
If it's till not starting correctly I'd recommend to remove device providers (starting with asus) and see if it's something device-specific causing the issues.

**Comment by Dadudze123** [comment]
ASUS is causing issues, but none of my hardware is showing in RGBSync+

**Comment by Dadudze123** [comment]
I have fixed it (just launched razer synapse), now it just doesn't detect keyboard and I have weird problem... I have no "Sync-L
![2019 02 22-11 20](https://user-images.githubusercontent.com/23727027/53236354-5b84cb80-3694-11e9-8f8c-e7629e31b42b.png)
ED"

**Comment by Dadudze123** [comment]
And count of LED in mouse is weridly big
