### ISSUE TITLE
No "Sync-LED"

### ISSUE THREAD

**Issue by Dadudze123** [DarthAffe/RGBSyncPlus#36]
I have unblocked ZIP and run as admin, but there is nothing in "Sync-LED"
![53236354-5b84cb80-3694-11e9-8f8c-e7629e31b42b](https://user-images.githubusercontent.com/23727027/53760928-848f3280-3ec4-11e9-9c62-5e5cde095f96.png)

**Comment by Meteoryte** [comment]
Same issue here

**Comment by DarthAffe** [comment]
Razer doesn't support reading led-colors from devices, that's why it's not in the sync-led list.

**Comment by Dadudze123** [comment]
Thanks for help.
